# Generated by Django 5.1.2 on 2024-10-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Technical Task'), (2, 'User Story')])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prio', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'Urgent')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
