# Generated by Django 5.1.3 on 2024-12-09 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], max_length=10)),
                ('status', models.CharField(choices=[('toDo', 'To Do'), ('inProgress', 'In Progress'), ('done', 'Done'), ('awaitFeedback', 'Await Feedback')], max_length=20)),
                ('subTasks', models.JSONField(default=list)),
                ('contacts', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='JOIN_Backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contactId', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('add_name', models.CharField(max_length=100)),
                ('add_email', models.EmailField(max_length=254)),
                ('add_phone', models.CharField(max_length=20)),
                ('initials', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='JOIN_Backend.user')),
            ],
        ),
    ]
