# Generated by Django 5.1.3 on 2024-12-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JOIN_Backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='add_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='add_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone',
            new_name='add_phone',
        ),
    ]
