# Generated by Django 5.1.3 on 2024-12-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JOIN_Backend', '0003_task_contacts_task_subtasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='subtasks',
            new_name='subTasks',
        ),
    ]
