# Generated by Django 5.1.3 on 2024-12-06 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOIN_Backend', '0005_alter_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contactId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
