# Generated by Django 5.1.3 on 2024-12-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOIN_Backend', '0007_remove_contact_contactid_alter_contact_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AddField(
            model_name='contact',
            name='contactId',
            field=models.UUIDField(default='5f7d5cbe-39f9-4d9b-8e9d-b3e6d12f94d9', editable=False, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
